"""empty message

Revision ID: ae8f840cc666
Revises: 
Create Date: 2023-11-21 22:45:12.854222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae8f840cc666'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administration',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=True),
    sa.Column('lastName', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=7), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('client',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('firstName', sa.String(length=100), nullable=True),
    sa.Column('lastName', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('loan',
    sa.Column('loanId', sa.Integer(), nullable=False),
    sa.Column('requestDate', sa.Date(), nullable=True),
    sa.Column('loanOfficerResponse', sa.String(length=1000), nullable=True),
    sa.Column('committeResponse', sa.String(length=100), nullable=True),
    sa.Column('document', sa.String(length=100), nullable=True),
    sa.Column('loanType', sa.String(length=40), nullable=True),
    sa.Column('requestStatus', sa.String(length=50), nullable=True),
    sa.Column('loanOfficerEmail', sa.String(length=100), nullable=True),
    sa.Column('clientEmail', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['clientEmail'], ['client.email'], ),
    sa.ForeignKeyConstraint(['loanOfficerEmail'], ['administration.email'], ),
    sa.PrimaryKeyConstraint('loanId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan')
    op.drop_table('client')
    op.drop_table('administration')
    # ### end Alembic commands ###
