"""empty message

Revision ID: ca8c71ac43ec
Revises: ec35125cedc1
Create Date: 2024-01-13 20:52:12.721500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8c71ac43ec'
down_revision = 'ec35125cedc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthlySalary', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('requestedLoan', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('paymentPeriod', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('monthlyPaybackAmount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_column('monthlyPaybackAmount')
        batch_op.drop_column('paymentPeriod')
        batch_op.drop_column('requestedLoan')
        batch_op.drop_column('monthlySalary')

    # ### end Alembic commands ###
